version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: Jellyfish\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'
cache:
  - packages -> **\packages.config

before_build:
- cmd: >-
    nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    nuget pack Jellyfish\Jellyfish.csproj
artifacts:
  - path: .\*.nupkg
    name: NupkgArtifact
deploy:
  provider: NuGet
  api_key:
    secure: vc7rUEW84l4OwcpHh3cb+8CeSfkYRwzp7h1VFjfHeMtYve2r0erWtueexTARgvxr
  skip_symbols: true
  artifact: NupkgArtifact
