version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'Jellyfish\*.csproj'
  version: '{version}'
  package_version: '{version}'
cache:
  - packages -> **\packages.config

before_build:
- cmd: >-
    nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    nuget pack Jellyfish\Jellyfish.csproj
artifacts:
  - path: .\*.nupkg
    name: NupkgArtifact
deploy:
  provider: NuGet
  api_key:
    secure: vc7rUEW84l4OwcpHh3cb+8CeSfkYRwzp7h1VFjfHeMtYve2r0erWtueexTARgvxr
  skip_symbols: true
  artifact: /.*\.nupkg/
